name: Build and Deploy to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm ci
      - run: npm run build
